/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef CLICK4_0_PRIVATE_H
#define CLICK4_0_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"4.6.0.87"
#define VER_MAJOR	4
#define VER_MINOR	6
#define VER_RELEASE	0
#define VER_BUILD	87
#define COMPANY_NAME	""
#define FILE_VERSION	"4.6.0.87"
#define FILE_DESCRIPTION	"Click IDE 4.6 - Insider"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"4.6.0.87"

#endif /*CLICK4_0_PRIVATE_H*/
